// Generated by CoffeeScript 1.6.2
(function() {
  var findExtension, module, path;

  module = require('module');

  path = require('path');

  findExtension = function(filename) {
    var extension, extensions, thisExtension;

    extension = null;
    extensions = path.basename(filename).split('.');
    if (extensions[0] === '') {
      extensions.shift();
    }
    while (extensions.shift()) {
      thisExtension = '.' + extensions.join('.');
      if (module._extensions[thisExtension]) {
        extension = thisExtension;
        break;
      }
    }
    return extension || '.js';
  };

  module.prototype.load = function(filename) {
    var extension;

    this.filename = filename;
    this.paths = module._nodeModulePaths(path.dirname(filename));
    extension = findExtension(filename);
    module._extensions[extension](this, filename);
    return this.loaded = true;
  };

}).call(this);
